# Generated by Django 4.1.6 on 2023-05-23 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donationboxdashboard', '0002_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
