# Generated by Django 4.2.1 on 2023-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationboxdashboard', '0003_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationpic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='donor',
            name='userpic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='deliverypic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='idpic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='userpic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
