from django.urls import path
from . import views
urlpatterns = [


    path('all_logins', views.all_logins, name='all_logins'),
    path('donor_reg', views.donor_reg, name='donor_reg'),
    path('donorlogin', views.donor_login, name='donorlogin'),
    path('volunteer_login', views.volunteer_login, name='volunteer_login'),
    path('admin_login', views.admin_login, name='admin_login'),
    path('donor_home', views.donor_home, name='donor_home'),
    path('logout/', views.Logout, name='logout'),
    path('donate_now', views.donate_now, name='donate_now'),
    path('donation_history', views.donation_history, name='donation_history'),
    path('changepwd_donor', views.changepwd_donor, name='changepwd_donor'),
    path('admin_home', views.admin_home, name='admin_home'),
    path('pending_donation', views.pending_donation, name='pending_donation'),
    path('view_donationdetail/<int:pid>',
         views.view_donationdetail, name='view_donationdetail'),
    path('accepted_donation', views.accepted_donation, name='accepted_donation'),
    path('accepted_donationdetail/<int:pid>',
         views.accepted_donationdetail, name='accepted_donationdetail'),
    path('rejected_donation', views.rejected_donation, name='rejected_donation'),
    path('volunteer_reg', views.volunteer_reg, name='volunteer_reg'),
    path('volunteer_home', views.volunteer_home, name='volunteer_home'),
    path('manage_donor', views.manage_donor, name='manage_donor'),
    path('view_donordetail/<int:pid>',
         views.view_donordetail, name='view_donordetail'),
    path('new_volunteer', views.new_volunteer, name='new_volunteer'),
    path('view_volunteerdetail/<int:pid>',
         views.view_volunteerdetail, name='view_volunteerdetail'),
    path('accepted_volunteer', views.accepted_volunteer, name='accepted_volunteer'),
    path('rejected_volunteer', views.rejected_volunteer, name='rejected_volunteer'),
    path('add_area', views.add_area, name='add_area'),
    path('manage_area', views.manage_area, name='manage_area'),
    path('edit_area/<int:pid>', views.edit_area, name='edit_area'),
    path('delete_area/<int:pid>', views.delete_area, name='delete_area'),
    path('changepwd_admin', views.changepwd_admin, name='changepwd_admin'),
    path('accepted_donationdetail/<int:pid>',
         views.accepted_donationdetail, name='accepted_donationdetail'),
    path('volunteerallocated_donation', views.volunteerallocated_donation,
         name='volunteerallocated_donation'),
    path('delete_donor/<int:pid>', views.delete_donor, name='delete_donor'),
    path('changepwd_volunteer', views.changepwd_volunteer,
         name='changepwd_volunteer'),
    path('collection_req', views.collection_req, name='collection_req'),
    path('donationcollection_detail/<int:pid>',
         views.donationcollection_detail, name='donationcollection_detail'),
    path('donationrec_volunteer', views.donationrec_volunteer,
         name='donationrec_volunteer'),
    path('donationrec_detail/<int:pid>',
         views.donationrec_detail, name='donationrec_detail'),
    path('donationnotrec_volunteer', views.donationnotrec_volunteer,
         name='donationnotrec_volunteer'),
    path('donationdelivered_volunteer', views.donationdelivered_volunteer,
         name='donationdelivered_volunteer'),
    path('profile_volunteer', views.profile_volunteer, name='profile_volunteer'),
    path('donationrec_admin', views.donationrec_admin, name='donationrec_admin'),
    path('donationnotrec_admin', views.donationnotrec_admin,
         name='donationnotrec_admin'),
    path('donationdelivered_admin', views.donationdelivered_admin,
         name='donationdelivered_admin'),
    path('donationdetail_donor/<int:pid>',
         views.donationdetail_donor, name='donationdetail_donor'),
    path('profile_donor', views.profile_donor, name='profile_donor'),
    path('gallery', views.gallery, name='gallery'),
    path('all_donations', views.all_donations, name='all_donations'),
    path('delete_donation/<int:pid>',
         views.delete_donation, name='delete_donation'),
    path('all_volunteer', views.all_volunteer, name='all_volunteer'),
    path('delete_volunteer/<int:pid>',
         views.delete_volunteer, name='delete_volunteer'),


    path('request_donation/', views.request_donation, name='request_donation'),
    path('review_requests/', views.review_requests, name='review_requests'),
    path('approve_request/<int:request_id>/',
         views.approve_request, name='approve_request'),
    path('deny_request/<int:request_id>/',
         views.deny_request, name='deny_request'),

    path('my_requests/', views.my_requests, name='my_requests'),

    path('volunteer_profile/', views.volunteer_profile, name='volunteer_profile'),
    path('volunteer_profile_details/', views.volunteer_profile_details,
         name='volunteer_profile_details'),
    path('update_volunteer_profile/', views.update_volunteer_profile,
         name='update_volunteer_profile')


]
